### ISSUE TITLE
Running non-node scripts

### ISSUE THREAD

**Issue by generalov** [JacksonGariety/gulp-nodemon#29]
nodemon can also be used to execute and monitor other programs. For example:

    nodemon --exec "python -v" ./app.py

I want to run my python backend with gulp:

    gulp.task('backend', function() {
        nodemon({
            exec: 'python application.py --port=8000',
            watch: ['**/*.py', 'templates/**/*.html'],
            ext: 'py html',
        });
    });

But gulp crashed. There is log messages from console:
    
    [gulp] Finished 'default' after 11 μs
    [gulp] [nodemon] v1.0.20
    [gulp] [nodemon] to restart at any time, enter `rs`
    [gulp] [nodemon] watching: **/*.py templates/**/*.html
    [gulp] [nodemon] starting `gulp python application.py --port=8000`
    [gulp] Using gulpfile ~/Projects/gulpfile.js
    [gulp] Task 'python' was not defined in your gulpfile but you tried to run it.
    [gulp] Please check the documentation for proper gulpfile formatting.
    [gulp] [nodemon] app crashed - waiting for file changes before starting...

Note the gulp prepends exec command with 'gulp '.

I want to port my Gruntfile.js to gulpfile.js.  I use this Gruntfile.js https://gist.github.com/generalov/c4fd618ebf8a98d17cbe to run frontend (connect) and backend (python) with single command and achive the "livereload" functionality for both. I use grunt-conncurrent to run both nodemon and watch tasks together:
 
    grunt.initConfig({
        concurrent: {
            dev: {
                tasks: ['nodemon:dev', 'watch'],
                options: {
                    logConcurrentOutput: true
                }
            }
        }, 
        nodemon: {
            dev: {
                options: {
                    exec: 'python application.py --port=8000',
                    watch: ['**/*.py', 'templates/**/*.html'],
                    ext: 'py html',
                }
            },
         ...
     });

**Comment by LabiKyo** [comment]
Hi @JacksonGariety, I think you misunderstood. `exec` option is not the same as `child-process`. It's the exec nodemon would use, which is `node` by default.

I'm trying to use `babel-node` as exec, but got `Task 'babel-node' is not in your gulpfile`.

**Comment by JacksonGariety** [comment]
@LabiKyo would you post your gulpfile with the babel-node part included? I don't see a ref to babel-node in your original.

**Comment by LabiKyo** [comment]
Sure.

I create a new project to reproduce this. First `npm init` and install the following dependencies:
```javascript
{
    "babel": "^5.1.13",
    "gulp": "^3.8.11",
    "gulp-nodemon": "^2.0.2"
}
```

then create a gulpfile like this:
```javascript
var gulp = require('gulp');
var gulpNodemon = require('gulp-nodemon');

gulp.task('default', function () {
  return gulpNodemon({
    script: 'index.js',
    exec: './node_modules/.bin/babel-node',
  });
});
```

then `gulp`, I got `Task './node_modules/.bin/babel-node' is not in your gulpfile`

or use the global babel-node, it's the same.

```javascript
gulp.task('default', function () {
  return gulpNodemon({
    script: 'index.js',
    exec: 'babel-node',
  });
});
```

got `Task 'babel-node' is not in your gulpfile`

And here's how I can do this in command line with nodemon(`"nodemon": "^1.3.7"`)
```shell
./node_modules/.bin/nodemon --exec ./node_modules/.bin/babel-node index.js
```
it works.

**Comment by JacksonGariety** [comment]
@LabiKyo @generalov should be fixed in 2.0.3! Thanks, I must've left this in from pre-2.0 era gulp-nodemon.

**Comment by generalov** [comment]
Thanks!

**Comment by kellyrmilligan** [comment]
+1 this helped me with babel-node as well and gulp

**Comment by ibqn** [comment]
@JacksonGariety I still have this issue with `"gulp-nodemon": "^2.2.1"` exactly as @LabiKyo described.
